### ISSUE TITLE
Executing map function in parallel

### ISSUE THREAD

**Issue by deukyeon** [DICL/VeloxMR#33]

**Comment by vicentebolea** [comment]
Issue moved to [DICL/GurumPM #89](https://github.com/DICL/GurumPM/issues/89) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vicentebolea** [comment]
Issue moved to [DICL/GurumPM #90](https://github.com/DICL/GurumPM/issues/90) via [**ZenHub**](https://www.zenhub.com/)
